### ISSUE TITLE
Settings with sequence values clobber old values

### ISSUE THREAD

**Issue by rspeed** [rspeed/Django-MetaSettings#4]
Overview

---

Settings such as TEMPLATE_DIRS, MIDDLEWARE_CLASSES and INSTALLED_APPS use lists for values. It should be possible to ADD values to the values set by the inherited settings. This is not the optimal behavior, as parts of the values must be repeated.

Solution

---

When looping over the settings, check to see if the value is a list and already in the settings. If so, update the sequence (by the appropriate means) rather than replacing the value outright.

**Comment by matthewwithanm** [comment]
And if you want to override the sequence?

**Comment by rspeed** [comment]
How about this. To clobber a sequence:
    INSTALLED_APPS = (
        'django.matts.mom',
    )
And to amend it:
    INSTALLED_APPS += (
        'django.matts.mom',
    )

I think this could happen.

**Comment by rspeed** [comment]
Or really, just _run_ each settings file with the same scope in a bottom-up order.

**Comment by rspeed** [comment]
Fixed in SHA: 44ce84a6f8cecee8242b03e5b61b6a7d9b8dd410
